---
title: "Lab 01" 
subtitle: "Computing + Linear algebra review"
date: "08-31-2026"
date-format: "MMMM DD, YYYY"
footer: "[🔗 sta221-fa.github.io](https://sta221-fa26.github.io)"
logo: "../images/logo.png"
format: 
  revealjs:
    theme: slides.scss
    multiplex: false
    transition: fade
    slide-number: true
    incremental: false 
    chalkboard: true
execute:
  freeze: auto
  echo: true
knitr:
  opts_chunk: 
    R.options:      
    width: 200
---

## Today's lab {.midi}

**Topics**

- Review linear algebra concepts

- Data wrangling and visualizations in R

**Notes**

- Put all responses for computing questions in your `lab-01` Quarto document. You may write any mathematical work by hand and attach it to the rendered PDF before uploading to Gradescope.

## Find your teammates!

[Click here](https://prodduke-my.sharepoint.com/:x:/g/personal/mt324_duke_edu/IQA8clBbBs5XRLkbsoxVWW8aAQ0WFcxyggGecf_EvJpprQo?e=jpOT9e&nav=MTVfezAwMDAwMDAwLTAwMDEtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMH0) to see your teammates for Lab 01.

- Discuss the lab questions with your teammates

- Everyone write up the team's responses and submit your own Lab 01

## Tips for working on lab {.midi}

- Labs are **due at the end of your lab session**. **There is no late work or make ups accepted for lab.**

  - Push final changes to GitHub

  - Submit the PDF of your work in Gradescope.

- The lab will be graded based on attendance, submitting the lab, workflow & formatting, and correctness of 2 randomly selected questions.

  - For today's lab, we will grade one randomly selected question from the linear algebra review and one from the computing review.

## Workflow and formatting

Part of the lab grade is for “workflow & formatting” assessing the reproducible workflow and document format. This includes

- Having at least 2 informative commit messages (practicing version control)

  - There are markers in Lab 01 to help you incorporate version control in your workflow

- The PDF is neatly organized document with clear exercise headings and readable code and narrative

- The name (first and last), teammates' names, and date are updated at the top of the document.

## **When you’re done with lab**

- Make sure all your final changes have been pushed to your GitHub repo

- Submit your final PDF to Gradescope

  - Combine the rendered Quarto document and handwritten math work into a single PDF document if needed.

  - Access Gradescope through the course Canvas site

  - Mark the page(s) associated with each exercise

  - Mark the first page for "Attendance & submitting lab" and "Workflow & formatting"

## Getting started

Ask your TA if

- You do not have a `lab-01` repo in the GitHub course organization: [github.com/sta221-fa26](https://github.com/sta221-fa26)

- You need help cloning the repo and starting a new RStudio project

🔗 [sta221-fa26.github.io/labs/lab-01.html](../labs/lab-01.html)

## Reminder to submit your lab

<br>

::: callout-important
Be sure to submit your lab to Gradescope before leaving today!
:::
