---
title: "HW 02: Multiple linear regression"
subtitle: "Physical activity and post-COVID-19 conditions"

bibliography: references.bib
---

::: callout-important
## Due date

This assignment is due on **Thursday, September 24 at 11:59pm**. To be considered on time, the following must be done by the due date:

- Final `.qmd` and `.pdf` files pushed to your GitHub repo
- Final `.pdf` file submitted on Gradescope
:::

# Introduction

In this assignment, you will explore mathematical properties of multiple linear regression and use regression to explore factors related to daily physical activity among individuals with a post-COVID-19 condition.

# **Learning goals**

In this assignment, you will…

- explore mathematical properties of linear regression models.
- use multiple linear regression to model the relationship between three or more variables
- fit and interpret models with interaction terms.

# **Getting started**

- Go to the [sta221-fa26](https://github.com/sta221-fa26) organization on GitHub. Click on the repo with the prefix **hw-02**. It contains the starter documents you need to complete the assignment.

- Clone the repo and start a new project in RStudio. See the [Lab 00 instructions](../labs/lab-00.html) for details on cloning a repo and starting a new project in R.

# Packages

The following packages are used in this assignment:

```{r}
#| include: false

library(tidyverse)
library(tidymodels)
library(knitr)

# load other packages as needed
```

# Conceptual exercises

::: callout-important
## Instructions

The conceptual exercises are focused on explaining concepts and showing results mathematically. Show your work for each question.

**You may write the answers and associated work for conceptual exercises by hand or type them in your Quarto document.**
:::

## Exercise 1

a.  Show that the following is true for the vector of residuals: $\mathbf{e} = (\mathbf{I} - \mathbf{H})\boldsymbol{\epsilon}$

b.  Use the result from part (a) to derive $E(\mathbf{e})$.

c.  Use the result from part (a) to derive $Var(\mathbf{e})$.

## Exercise 2

Show how $\boldsymbol{\epsilon}$ being normally distributed means that $\hat{\boldsymbol{\beta}}$ is normally distributed.

## Exercise 3

*This exercise is adapted from @montgomery2021introduction*.

Suppose we fit the model $\mathbf{y} = \mathbf{X}_1\boldsymbol{\beta}_1 + \boldsymbol{\epsilon}$ when the true model is actually given by $\mathbf{y} = \mathbf{X}_1\boldsymbol{\beta}_1 + \mathbf{X}_2\boldsymbol{\beta}_2 + \boldsymbol{\epsilon}$. Assume $E(\boldsymbol{\epsilon}) = \mathbf{0}$ for both models.

a.  Find $E(\hat{\boldsymbol{\beta}}_1)$, the expected value of the least-squares estimator $\hat{\boldsymbol{\beta}}_1$.

b.  Under what condition does $E(\hat{\boldsymbol{\beta}}_1) = \boldsymbol{\beta}_1$? What is the relationship between $\mathbf{X}_1$ and $\mathbf{X}_2$ under this condition?

## Exercise 4

We conduct least-squares regression analysis with certain assumptions underlying the regression model. Consider ordinary least-squares regression model:

$$
\mathbf{y} = \mathbf{X}\boldsymbol{\beta} + \boldsymbol{\epsilon}, \quad \boldsymbol{\epsilon} \sim N(\mathbf{0}, \sigma^2\mathbf{I})
$$ {#eq-reg-model}

This model relies on four assumptions:

- **Linearity:** There is a linear relationship between the response and predictor variables.

- **Constant Variance:** The variability about the least squares line is constant for every value of the predictor.

- **Normality:** The distribution of the residuals is approximately normal.

- **Independence:** The residuals are independent from one another.

For each condition, state the components of @eq-reg-model that are used to represent it.

# Applied exercises

::: callout-important
## Instructions

The applied exercises focus on using the methods from the course to analyze data and answer questions about real-world phenomena.

**All work for the applied exercises must be typed in your Quarto document. Remember to render, commit, and push your work to GitHub regularly.**

Write all narrative responses using complete sentences. Include informative axis labels and titles on all visualizations.
:::

## Data: Physical activity in post-COVID-19 condition

In the academic article ["Physical activity in post-COVID-19 condition: A cross-sectional study"](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0357465#abstract0), @kopp2026 use multiple linear regression to study variability in the amount of daily physical activity among adults experiencing a post-COVID-19 condition (PCC). They define PCC based on the World Health Organization's definition as a "spectrum of symptoms that persist for three months or longer following a \[COVID-19\] infection and cannot be explained by an alternative diagnosis." Common symptoms include fatigue, dyspnea (shortness of breath), concentration difficulties, among others.

The data include the baseline measurements for 141 adults who participated in a clinical trial and are included in the article's analysis. This article focuses on understanding the level of the participants' physical activity based on demographic information and factors related to PCC measured by previously validated survey instruments. Physical activity is measured by the 24-hour Euclidean Norm Minus One (mean 24h ENMO). This is derived based on accelerometer data and is a reflection of the overall physical activity across an entire day.

The analysis will focus on the variables below. The definitions are in the codebook provided by the authors.

- `mean_ENMO_per_person`: Mean ENMO (mg) value over at least 4 days with at least one weekend day for each participant (measured in milligravity, mg)

- `chron_symp_disease`: Physician-diagnosed chronic symptomatic disease (`Ja` (yes), `Nein` (no))

- `sex` : Sex ( `Female` or `Male`)

- `age`: Age in years (ranges from 18 to 80)

- `edu_t0`: Education

  - `Lower secondary`: Compulsory school

  - `Upper secondary`: Vocational training or Baccalaureate

  - `Tertiary`: Technical college or higher technical college or University

- `sts_reps_t1` :Number of repetitions during the 30-second Sit-to-Stand test

  - Measure of functional capacity

- `longcov_pem_grade_t1` : Post-exertional malaise symptom grade (PEM) measured on Likert scale questionnaire

- Columns starting with `facit_` : 13 Likert scale items from Functional Assessment of Chronic Illness Therapy Fatigue (FACIT-Fatigue) instrument. See [the codebook](https://doi.org/10.1371/journal.pone.0357465.s003) for full details on the questions.

[Click here](https://doi.org/10.1371/journal.pone.0357465.s003) to access the full codebook.

The raw data were provided by the authors and are available in `physical-activity-post-covid.csv` in the `data` folder of your repo.

::: callout-note
## Analysis goal

**Our goal is to reproduce the researcher's regression analysis on the mean 24h ENMO and extend the analysis by considering a potential interaction effect.**
:::

## Exercise 5

We would like to reproduce the regression model for mean ENMO shown in [Table 4](https://doi.org/10.1371/journal.pone.0357465.t004) of the article. In order to do so, we start with data processing to prepare the data for the model.

a.  Conduct the following data processing steps used by the authors to prepare the data for analysis:

    - Refactor `chron_symp_disease`, so that `Nein` is the baseline level.

    - The authors use three levels for education in the model. Create a new variable that summarizes `edu_t0` into three levels: `Lower secondary`, `Upper secondary`, `Tertiary`. Refer to the data dictionary to see how the authors categorize the levels of `edu_t0`.

    - The original data contains the data for each of the 13 items on the Functional Assessment of Chronic Illness Therapy Fatigue (FACIT-Fatigue) instrument [@montan2018]. We wish to compute an overall assessment score for the model. To do so, compute the sum for the 13 assessment items. The possible scores for the assessment total are 0 (severe fatigue) to 52 (no fatigue).

b.  Fit the linear regression model using presence of diagnosed chronic symptoms, sex, age, functional capacity, severity of fatigue, severity of PEM, and education to explain variability in mean ENMO. Display the model output to 2 decimal places. The model should match the results in [Table 4](https://doi.org/10.1371/journal.pone.0357465.t004) of the article. (Note: The authors do not print the intercept.)

## Exercise 6

a.  Interpret the coefficient of `sts_reps_t1` in the context of the data.

b.  Interpret the coefficient of `Upper secondary` in the context of the data.

## Exercise 7

We wish to expand on the analysis from the article by considering an interaction between the presence of a diagnosed chronic illness and functional capacity.

a.  Create a visualization that can be used to explore this potential interaction effect. Use the visualization to comment on whether there appears to be an interaction between these two variables.

b.  Fit a model using the predictors from Exercise 5 along with this interaction effect. Neatly display the model using 2 decimal places.

c.  Interpret the coefficient for the interaction term.

d.  Interpret the effect of functional capacity for individuals with a diagnosed chronic illness.

## Exercise 8

Which model is a better fit for the data - the model in Exercise 5 or the model in Exercise 7? Briefly explain your choice using relevant statistics to support your response.

# AI disclosure

Did you use an LLM / Generative AI tool to complete this assignment? If not, copy and paste the first option in your Quarto document. Otherwise, copy and paste [**all**]{.underline} statements that describe how you used it. The purpose of the disclosure is for you to reflect on how you’re using AI in this course. It also helps me learn how students are most effectively using AI.

- I didn't use an LLM / Generative AI tool.
- I asked it to clarify one or more exercises.
- I asked it clarifying questions to better understand a concept.
- I asked it to help write code to complete an exercise.
- I gave it my code and asked it to help me fix it.
- I asked it about an error or why code would do something I didn't want.
- I pasted the exercise prompt in AI and asked for help, but I wrote my answer myself.
- I pasted the exercise prompt in AI and copied and pasted at least some of the answer into my Quarto document.
- Other:\_\_\_\_\_\_

# Submission

::: callout-important
Before you wrap up the assignment, make sure all documents are updated on your GitHub repo. We will be checking these to make sure you have been practicing how to commit and push changes.

Remember -- you must turn in a PDF file to the Gradescope page before the submission deadline for full credit.

If you write your responses to conceptual exercises by hand, you will need to combine your written work to the completed PDF for the applied exercises before submitting on Gradescope.

Instructions to combine PDFs:

- Preview (Mac): [support.apple.com/guide/preview/combine-pdfs-prvw43696/mac](https://support.apple.com/guide/preview/combine-pdfs-prvw43696/mac)

- Adobe (Mac or PC): [helpx.adobe.com/acrobat/using/merging-files-single-pdf.html](https://helpx.adobe.com/acrobat/using/merging-files-single-pdf.html)

  - Get free access to Adobe Acrobat as a Duke student: [oit.duke.edu/help/articles/kb0030141/](https://oit.duke.edu/help/articles/kb0030141/)
:::

To submit your assignment:

- Access Gradescope through the menu on the [STA 221 Canvas site.](https://canvas.duke.edu/courses/84458)

- Click on the assignment, and you’ll be prompted to submit it.

- Mark the pages associated with each exercise. All of the pages of your assignment should be associated with at least one question (i.e., should be “checked”).

- Select the first page of your .PDF submission to be associated with the *“Workflow & formatting”* and "AI Disclosure" sections.

# Grading (25 points)

| Component                    | Points |
|------------------------------|--------|
| Selected conceptual exercise | 10     |
| Selected applied exercise    | 10     |
| Completing AI Disclosure     | 1      |
| Workflow & formatting        | 4      |

The "Workflow & formatting" grade is to assess the reproducible workflow and document format for the applied exercises. This includes having at least 3 informative commit messages, a neatly organized document with readable code, along with your name and the date updated in the YAML.
