{
  "hash": "a33e693e371e54bc45879efaeb1be0a0",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Inference for regression\"\nsubtitle: \"Confidence intervals\"\nauthor: \"Prof. Maria Tackett\"\ndate: \"September 29, 2026\"\ndate-format: \"MMM DD, YYYY\"\nfooter: \"[🔗 sta221-fa26.github.io](https://sta221-fa26.github.io)\"\nlogo: \"../images/logo.png\"\nformat: \n  revealjs: \n    theme: slides.scss\n    multiplex: false\n    transition: fade\n    slide-number: true\n    incremental: false \n    chalkboard: true\n    include-before: [ '<script type=\"text/x-mathjax-config\">MathJax.Hub.Config({tex2jax: {enableAssistiveMml: false}});</script>']\n  html: \n    output-file: 11-confidence-intervals-notes.html\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\nexecute:\n  freeze: auto\n  echo: true\nknitr:\n  opts_chunk: \n    R.options:      \n    width: 200\nbibliography: references.bib\n---\n\n\n\n## Announcements\n\n- [Project proposal](../project.html) due TODAY at 11:59pm (on GitHub)\n\n- [HW 03](../hw/hw-03.html) due Thursday, October 1 at 11:59pm\n\n- Exam 01 on Tuesday, October 6 in-class\n\n- [Statistics experience](../hw/hw-stats-experience) due Tuesday, November 24\n\n  - Survey link updated in instructions\n\n## Topics\n\n- Confidence interval for a coefficient $\\beta_j$\n\n## Computing setup\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# load packages\nlibrary(tidyverse)  \nlibrary(tidymodels)  \nlibrary(knitr)       \nlibrary(kableExtra)  \nlibrary(patchwork)   \n\n# set default theme in ggplot2\nggplot2::theme_set(ggplot2::theme_bw())\n```\n:::\n\n\n## Data: NCAA Football expenditures {.midi}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfootball <- read_csv(\"data/ncaa-football-exp.csv\")\n```\n:::\n\n\nToday's data come from [Equity in Athletics Data Analysis](https://ope.ed.gov/athletics/#/datafile/list) and includes information about sports expenditures and revenues for colleges and universities in the United States. This data set was featured in a [March 2022 Tidy Tuesday](https://github.com/rfordatascience/tidytuesday/blob/master/data/2022/2022-03-29/readme.md).\n\nWe will focus on the 2019 - 2020 season expenditures on football for 127 institutions in the NCAA - Division 1 FBS. The variables are\n\n- `total_exp_m`: Total expenditures on football in the 2019 - 2020 academic year (in millions USD)\n\n- `enrollment_th`: Total student enrollment in the 2019 - 2020 academic year (in thousands)\n\n- `type`: institution type (Public or Private)\n\n\n\n## Regression model\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nexp_fit <- lm(total_exp_m ~ enrollment_th + type, data = football)\ntidy(exp_fit) |>\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term          | estimate| std.error| statistic| p.value|\n|:-------------|--------:|---------:|---------:|-------:|\n|(Intercept)   |   19.332|     2.984|     6.478|       0|\n|enrollment_th |    0.780|     0.110|     7.074|       0|\n|typePublic    |  -13.226|     3.153|    -4.195|       0|\n\n\n:::\n:::\n\n\n## Steps for a hypothesis test\n\n1.  State the null and alternative hypotheses.\n2.  Compute a test statistic.\n3.  Compute the p-value.\n4.  State the conclusion.\n\n## Hypothesis test for $\\beta_\\text{public}$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|term          | estimate| std.error| statistic| p.value|\n|:-------------|--------:|---------:|---------:|-------:|\n|(Intercept)   |   19.332|     2.984|     6.478|       0|\n|enrollment_th |    0.780|     0.110|     7.074|       0|\n|typePublic    |  -13.226|     3.153|    -4.195|       0|\n\n\n:::\n:::\n\n\n# Confidence interval for $\\beta_j$\n\n## Confidence interval for $\\beta_j$ {.midi}\n\n::: incremental\n- A plausible range of values for a population parameter is called a **confidence interval**\n\n- Using only a single point estimate is like fishing with a fishing line, and using a confidence interval is like fishing with a net\n\n  - We put the line where we saw a fish but we will probably miss, if we use a net in that area, we have a good chance of catching the fish\n:::\n\n![Image generated by ChatGPT 6-Luna](images/clipboard-281042674.png){fig-align=\"center\"}\n\n## Confidence interval for $\\beta_j$ \n\n![Image generated by ChatGPT 6-Luna](images/11-fishing-ci.png)\n\nSimilarly, if we report a point estimate, we probably will not hit the exact population parameter, but if we report a range of plausible values we have a good shot at capturing the parameter\n\n## What \"confidence\" means {.midi}\n\n::: incremental\n- We will construct $C\\%$ confidence intervals.\n\n  - The confidence level impacts the width of the interval\n\n- \"Confident\" means if we were to take repeated samples of the same size as our data, fit regression lines using the same predictors, and calculate $C\\%$ CIs for the coefficient of $x_j$, then $C\\%$ of those intervals will contain the true value of the coefficient $\\beta_j$\n\n- Balance precision and accuracy when selecting a confidence level\n:::\n\n## Your turn\n\n::: question\nWhat is the probability $\\beta_j$ is in the 95% confidence interval\n\n- pre data collection?\n- post data collection?\n:::\n\n![](images/september-29-qrcode.png){fig-align=\"center\" width=\"30%\"}\n\n::: center\n[`https://app.wooclap.com/GFGFXBZ`{=html}](https://app.wooclap.com/GFGFXBZ)\n:::\n\n## Confidence interval for $\\beta_j$\n\n$$\n\\text{Estimate} \\pm \\text{ (critical value) } \\times \\text{SE}\n$$\n\n. . .\n\n$$\n\\hat{\\beta}_1 \\pm t^* \\times SE_{\\hat{\\beta}_j}\n$$\n\nwhere $t^*$ is calculated from a $t$ distribution with $n-p-1$ degrees of freedom\n\n## Confidence interval: Critical value\n\n::: {.fragment fragment-index=\"1\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# confidence level: 95%\nqt(0.975, df = nrow(football) - 2 - 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.97928\n```\n\n\n:::\n:::\n\n:::\n\n<br>\n\n::: {.fragment fragment-index=\"2\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# confidence level: 90%\nqt(0.95, df = nrow(football) - 2 - 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.657235\n```\n\n\n:::\n:::\n\n:::\n\n<br>\n\n::: {.fragment fragment-index=\"3\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# confidence level: 99%\nqt(0.995, df = nrow(football) - 2 - 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.61606\n```\n\n\n:::\n:::\n\n:::\n\n## 95% CI for $\\beta_\\text{enroll}$: Calculation\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|term          | estimate| std.error| statistic| p.value|\n|:-------------|--------:|---------:|---------:|-------:|\n|(Intercept)   |   19.332|     2.984|     6.478|       0|\n|enrollment_th |    0.780|     0.110|     7.074|       0|\n|typePublic    |  -13.226|     3.153|    -4.195|       0|\n\n\n:::\n:::\n\n\n## 95% CI for $\\beta_j$ in R\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntidy(exp_fit, conf.int = TRUE, conf.level = 0.95) |> \n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term          | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:-------------|--------:|---------:|---------:|-------:|--------:|---------:|\n|(Intercept)   |   19.332|     2.984|     6.478|       0|   13.426|    25.239|\n|enrollment_th |    0.780|     0.110|     7.074|       0|    0.562|     0.999|\n|typePublic    |  -13.226|     3.153|    -4.195|       0|  -19.466|    -6.986|\n\n\n:::\n:::\n\n\n**Interpretation**: We are 95% confident that for each additional 1,000 students enrolled, the institution's expenditures on football will be greater by \\$562,000 to \\$999,000, on average, holding institution type constant.\n\n## Confidence intervals & hypothesis tests {.midi}\n\n- A $C\\%$ confidence interval corresponds to a two-sided hypothesis test with $\\alpha$-level of $(100 - C)\\%$\n\n- Using a confidence interval for a two-sided test:\n\n  - If the hypothesized value is in the interval $\\Rightarrow$ Fail to reject $H_0$\n\n  - If the hypothesized value is not in the interval $\\Rightarrow$ Reject $H_0$\n\n<br>\n\n::: question\nThe 95% confidence interval for `typePublic` is -19.466 to -6.986. Do we reject or fail to reject the null hypothesis that $\\beta_{\\text{typePublic}} = 0$ ?\n:::\n\n## Recap\n\n- Constructed and interpreted a confidence interval for a coefficient $\\beta_j$\n\n## Before next class\n\n- Complete project proposal (submit by pushing to GitHub repo)\n\n- No prepare assignment\n",
    "supporting": [
      "11-confidence-intervals_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}