{
  "hash": "214f0d9af86430432d47c68826dd5c14",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Multiple linear regression\"\nauthor: \"Prof. Maria Tackett\"\ndate: \"09-08-2026\"\ndate-format: \"MMMM DD, YYYY\"\nfooter: \"[🔗 sta221-fa26.github.io](https://sta221-fa26.github.io)\"\nlogo: \"../images/logo.png\"\nformat: \n  revealjs: \n    theme: slides.scss\n    multiplex: false\n    transition: fade\n    slide-number: true\n    incremental: false \n    chalkboard: true\n    include-before: [ '<script type=\"text/x-mathjax-config\">MathJax.Hub.Config({tex2jax: {enableAssistiveMml: false}});</script>']\n  html: \n    output-file: 05-mlr-notes.html\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\n\nexecute:\n  freeze: auto\n  echo: true\nknitr:\n  opts_chunk: \n    R.options:      \n    width: 200\nbibliography: references.bib\n---\n\n## Announcements\n\n- HW 01 **due Thursday, September 10 at 11:59pm**\n  - Reminder: [One-time late waiver for HW](https://sta221-fa26.github.io/syllabus.html#one-time-late-waiver)\n\n## Topics\n\n- Introducing multiple linear regression\n\n  - Exploratory data analysis for multiple linear regression\n  - Fitting the least squares line\n  - Interpreting coefficients for quantitative predictors\n  - Prediction\n\n- Comparing models\n\n## Computing setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load packages\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(openintro)\nlibrary(patchwork)\nlibrary(knitr)\nlibrary(kableExtra)\n\n# set default theme and larger font size for ggplot2\nggplot2::theme_set(ggplot2::theme_minimal(base_size = 14))\n```\n:::\n\n\n## Data: Lemurs\n\n\n::: {.cell}\n\n:::\n\n\n::: midi\nToday’s data contains a subset of the original Duke Lemur data set available in the [TidyTuesday GitHub repo](https://github.com/rfordatascience/tidytuesday/blob/master/data/2021/2021-08-24/readme.md). This data includes information on 252 lemurs less than 24 months old from three taxa:\n\n- Eulemur rufus (ERUF), commonly known as Red-fronted brown lemur\n- Propithecus coquereli (PCOQ), commonly known as Coquerel’s sifaka\n- Varecia rubra (VRUB), commonly known as Red ruffed lemur.\n:::\n\n:::::: columns\n::: {.column width=\"33%\"}\n![ERUF](images/06-eruf-lemur.jpg){fig-align=\"center\"}\n:::\n\n::: {.column width=\"33%\"}\n![PCOQ](images/06-pcoq-lemur.jpg){fig-align=\"center\"}\n:::\n\n::: {.column width=\"33%\"}\n![VRUB](images/06-vrub-lemur.png){fig-align=\"center\"}\n:::\n::::::\n\n::: small\nImages from [Duke Lemur Center - Meet the Lemurs](Duke%20Lemur%20Center.%20n.d.%20“Meet%20the%20Lemurs.”%20https://lemur.duke.edu/discover/meet-the-lemurs/)\n:::\n\n## Variables\n\n::: midi\n**Predictors**:\n\n- `taxon` : Code made as a combination of the lemur’s genus and species. Note that the genus is a broader categorization that includes lemurs from multiple species. (`ERUF`: Eulemur rufus, `PCOQ`: Propithecus coquereli, `VRUB`: Varecia rubra)\n- `sex` : Sex of the lemur (`M`: Male, `F`: Female)\n- `age`: Age of the lemur when weight was recorded (in months)\n- `litter_size`: Total number of infants in the litter the lemur was born into (this includes the observed lemur)\n\n**Response**: `weight`: Weight of the lemur (in grams)\n:::\n\n## Response: `weight`\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](05-mlr_files/figure-revealjs/unnamed-chunk-2-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n| Min| Median|  Max|  IQR|\n|---:|------:|----:|----:|\n| 131| 1779.5| 6969| 2087|\n\n\n:::\n:::\n\n\n## Predictors\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](05-mlr_files/figure-revealjs/unnamed-chunk-4-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n## Response vs. predictors\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](05-mlr_files/figure-revealjs/unnamed-chunk-5-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n. . .\n\n::: midi\n**Goal**: Use age, taxon, and litter size to understand variability in the weight of lemurs younger than 24 months old.\n:::\n\n. . .\n\n:::: question\n::: midi\nWhy do we want to use a single model versus 3 separate simple linear regression models?\n:::\n::::\n\n# Multiple linear regression (MLR)\n\n## Multiple linear regression (MLR)\n\nBased on the analysis goals, we will use a **multiple linear regression** model of the following form\n\n$$\\begin{aligned}\\text{weight} ~ = \n\\beta_0 & + \\beta_1 ~ \\text{age} \\\\ & + \\beta_2 ~ \\text{taxon}_1 \\\\ &+ \\beta_3 ~ \\text{taxon}_2 \\\\\n&+\\beta_4~ \\text{litter_size} \\\\\n& +\\epsilon\n\\end{aligned}$$\n\n## Multiple linear regression\n\n**Recall:** The simple linear regression model\n\n$$Y = \\beta_0 + \\beta_1~ X + \\epsilon$$\n\n. . .\n\nThe form of the multiple linear regression model is\n\n$$Y = \\beta_0 + \\beta_1X_1 +  \\dots + \\beta_pX_p + \\epsilon$$\n\n<br>\n\n. . .\n\nTherefore,\n\n$$E(Y|X_1, \\ldots, X_p) = \\beta_0 + \\beta_1X_1 +  \\dots + \\beta_pX_p$$\n\n## Fitting the least squares line\n\nSimilar to simple linear regression, we want to find estimates for $\\beta_0, \\beta_1, \\ldots, \\beta_p$ that minimize\n\n$$\\sum_{i=1}^{n}\\epsilon_i^2 = \\sum_{i=1}^n[y_i - \\hat{y}_i]^2 = \\sum_{i=1}^n[y_i - (\\beta_0 + \\beta_1x_{i1} + \\dots + \\beta_px_{ip})]^2$$\n\n<br>\n\n. . .\n\nThe calculations can be very tedious, especially if $p$ is large\n\n## Matrix form of MLR\n\nSuppose we have $n$ observations, a quantitative response variable, and $p$ \\> 1 predictors $$\\underbrace{\n\\begin{bmatrix}\ny_1 \\\\\n\\vdots \\\\\ny_n\n\\end{bmatrix} }_\n{\\mathbf{y}} \\hspace{3mm}\n= \n\\hspace{3mm}\n\\underbrace{\n\\begin{bmatrix}\n1 &x_{11} & \\dots & x_{1p}\\\\\n\\vdots & \\vdots &\\ddots & \\vdots \\\\\n1 &  x_{n1} & \\dots &x_{np}\n\\end{bmatrix}\n}_{\\mathbf{X}}\n\\hspace{2mm}\n\\underbrace{\n\\begin{bmatrix}\n\\beta_0 \\\\\n\\beta_1 \\\\\n\\vdots \\\\\n\\beta_p\n\\end{bmatrix}\n}_{\\boldsymbol{\\beta}}\n\\hspace{3mm}\n+\n\\hspace{3mm}\n\\underbrace{\n\\begin{bmatrix}\n\\epsilon_1 \\\\\n\\vdots\\\\\n\\epsilon_n\n\\end{bmatrix}\n}_\\boldsymbol{\\epsilon}$$\n\n::: question\nWhat are the dimensions of $\\mathbf{y}$, $\\mathbf{X}$, $\\boldsymbol{\\beta}$, $\\boldsymbol{\\epsilon}$?\n:::\n\n## Matrix form of multiple linear regression\n\nAs with simple linear regression, we have\n\n$$\\mathbf{y} = \\mathbf{X}\\boldsymbol{\\beta} + \\boldsymbol{\\epsilon}$$\n\n. . .\n\nGeneralizing the derivations from SLR to $p > 2$, we have\n\n$$\\hat{\\boldsymbol{\\beta}} = (\\mathbf{X}^\n \\mathsf{T}\\mathbf{X})^{-1}\\mathbf{X}^\\mathsf{T}\\mathbf{y}$$\n\nas before.\n\n## Your turn\n\n:::: question\n::: midi\nWhat are the dimensions of the hat matrix, $\\mathbf{H}$, in multiple linear regression?\n:::\n::::\n\n![](images/september-08-qrcode.png){fig-align=\"center\" width=\"35%\"}\n\n<center><https://app.wooclap.com/JETCCCB></center>\n\n## Model fit in R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlemur_fit <- lm(weight ~ age + taxon + litter_size,\n              data = lemurs)\n\ntidy(lemur_fit) |>\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |   -0.772|   116.993|    -0.007|   0.995|\n|age         |  137.479|     4.845|    28.377|   0.000|\n|taxonPCOQ   |  462.184|    95.287|     4.850|   0.000|\n|taxonVRUB   | 1020.390|   133.468|     7.645|   0.000|\n|litter_size |  -14.101|    65.756|    -0.214|   0.830|\n\n\n:::\n:::\n\n\n## Model equation\n\n$$\\begin{align}\\hat{\\text{weight}} = -0.772 &+137.479 \\times \\text{age}\\\\\n&+ 462.184 \\times \\text{taxonPCOQ}\\\\  \n&+ 1020.390 \\times \\text{taxonVRUB}\\\\\n& -14.101 \\times \\text{litter_size}\n\\end{align}$$\n\n::: callout-note\nWe will talk about why there are only two terms in the model for `taxon` soon!\n:::\n\n## Interpreting $\\hat{\\beta}_j$ {.midi}\n\n- The estimated coefficient $\\hat{\\beta}_j$ is the expected change in the mean of $Y$ when $X_j$ increases by one unit, <i><b>holding all else constant.</b></i>.\n\n. . .\n\n- **Example:** The estimated coefficient for `age` is 137.479. For each additional month in a young lemur’s age, their weight is expected to be greater by 137.479 grams, on average, holding taxon and litter size constant.\n\n::: callout-note\nAlternate interpretation: For each additional month in a young lemur’s age, their weight is expected to be greater by 137.479 grams, on average, adjusting for taxon and litter size.\n:::\n\n## Interpreting $\\hat{\\beta}_j$\n\n::: question\nThe estimated coefficient for `litter_size` is -14.101. Interpret this coefficient in the context of the data.\n:::\n\n<br>\n\n::: question\nWhy do we need to include a statement about holding all other predictors constant?\n:::\n\n## Interpreting $\\hat{\\beta}_0$\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:-----------|--------:|---------:|---------:|-------:|--------:|---------:|\n|(Intercept) |   -0.772|   116.993|    -0.007|   0.995| -231.203|   229.660|\n|age         |  137.479|     4.845|    28.377|   0.000|  127.937|   147.021|\n|taxonPCOQ   |  462.184|    95.287|     4.850|   0.000|  274.505|   649.862|\n|taxonVRUB   | 1020.390|   133.468|     7.645|   0.000|  757.510|  1283.271|\n|litter_size |  -14.101|    65.756|    -0.214|   0.830| -143.615|   115.414|\n\n\n:::\n:::\n\n\n. . .\n\n:::: question\n::: midi\nThe intercept is -0.772. What is a potential reason the intercept is negative though negative weight is not possible in practice?\n:::\n::::\n\n## Prediction\n\n::: question\nWhat is the predicted weight for a PCOQ lemur who is 10 months old and was born in a litter with 3 lemurs?\n:::\n\n<br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n-0.772 + 137.479  * 10 +462.184 * 1 + 1020.390 * 0 - 14.101 * 3\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1793.899\n```\n\n\n:::\n:::\n\n\n. . .\n\nThe predicted weight for this lemur is 1793.899 grams.\n\n## Prediction in R {.midi}\n\nJust like with simple linear regression, we can use the `predict()` function in R to calculate the appropriate intervals for our predicted values:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnew_lemur <- tibble(\n  age  = 10, \n  taxon = \"PCOQ\", \n  litter_size = 3\n)\n\npredict(lemur_fit, new_lemur)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       1 \n1793.898 \n```\n\n\n:::\n:::\n\n\n## Cautions\n\n- **Do not extrapolate!** Because there are multiple predictor variables, there is the potential to extrapolate in many directions\n- The multiple regression model only shows **association, not causality**\n  - To show causality, you must have a carefully designed experiment or carefully account for confounding variables in an observational study (causal inference)\n\n# Model comparison\n\n## Model evaluation: RMSE & $R^2$\n\n- **Root mean square error, RMSE**: A measure of the average error (average difference between observed and predicted values of the outcome)\n\n- **R-squared**, $R^2$ : Percentage of variability in the outcome explained by the regression model\n\n## Comparing models {.small}\n\nLet's consider the following models:\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term          |  Model 1|  Model 2|\n|:-------------|--------:|--------:|\n|(Intercept)   |   -0.772|  529.072|\n|age           |  137.479|   79.974|\n|taxonPCOQ     |  462.184| -361.629|\n|taxonVRUB     | 1020.390|  634.483|\n|litter_size   |  -14.101|  -32.108|\n|age:taxonPCOQ |       NA|   95.760|\n|age:taxonVRUB |       NA|   47.649|\n\n\n:::\n:::\n\n\n<br>\n\n<center>**How do we decide which model to choose?**</center>\n\n## Comparing models\n\n::: incremental\n- When comparing models, do we prefer the model with the lower or higher RMSE?\n\n- Though we use $R^2$ to assess the model fit, it is generally unreliable for comparing models with different number of predictors. Why?\n\n  - $R^2$ will stay the same or increase as we add more variables to the model.\n\n  - If we only use $R^2$ to choose a best fit model, we will be prone to choose the model with the most predictor variables.\n:::\n\n## Adjusted $R^2$\n\n- **Adjusted** $R^2$: measure that includes a penalty for unnecessary predictor variables\n- Similar to $R^2$, it is a measure of the amount of variation in the response that is explained by the regression model\n- Use the `glance()` function to get $Adj. R^2$ in R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglance(lemur_fit)$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7988424\n```\n\n\n:::\n:::\n\n\n## $R^2$ and Adjusted $R^2$\n\n$$R^2 = \\frac{SSM}{SST} = 1 - \\frac{SSR}{SST}$$\n\n<br>\n\n. . .\n\n$$R^2_{adj} = 1 - \\frac{SSR/(n-p-1)}{SST/(n-1)}$$\n\nwhere\n\n- $n$ is the number of observations used to fit the model\n\n- $p$ is the number of non-intercept terms in the model\n\n## Using $R^2$ and Adjusted $R^2$\n\n- Adjusted $R^2$ can be used as a quick assessment to compare the fit of multiple models; however, it should not be the only assessment\n- Use $R^2$ when describing the relationship between the response and predictor variables\n\n## Comparing models\n\n::::: columns\n::: {.column width=\"50%\"}\n**Model 1**\n\n**Model without interaction**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# r-squared\nglance(lemur_fit)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8020481\n```\n\n\n:::\n:::\n\n\n<br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# adj-r-squared\nglance(lemur_fit)$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7988424\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n**Model 2**\n\n**Model with interaction**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# r-squared\nglance(lemur_fit_2)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8443483\n```\n\n\n:::\n:::\n\n\n<br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# adj-r-squared\nglance(lemur_fit_2)$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8405364\n```\n\n\n:::\n:::\n\n:::\n:::::\n\n## Recap\n\n- Conducted exploratory data analysis for multiple linear regression\n\n- Used least squares to fit the regression line\n\n- Interpreted the coefficients for quantitative predictors\n\n- Predicted the response for new observations\n\n- Introduced $Adj. R^2$ for comparing models\n\n## Before next class\n\n- Complete [Lecture 06 prepare](../prepare/prepare-lec06.html)\n",
    "supporting": [
      "05-mlr_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}